### ISSUE TITLE
AfterEach

### ISSUE THREAD

**Issue by rich-glow** [VBA-tools/Excel-TDD#9]
It would be great if `AfterEach` functionality existed to be symmetrical with `BeforeEach`.

Is this on the roadmap?

**Comment by timhall** [comment]
I've definitely been thinking about it and have needed it for one of my projects, but it's been tricky to implement. The issue has been that there isn't really a way to know that a spec has finished in order to call `AfterEach`. I've played with calling it when the next spec is started, but couldn't find a way to call it the last time.

I'll look into it more and see what can be done.

**Comment by rich-glow** [comment]
awesome, thanks.
